### ISSUE TITLE
Dyndns ipv4 and ipv6

### ISSUE THREAD

**Issue by AlexeySa** [wl500g/wl500g#474] opened 2016-02-15 02:42 UTC
Please help. How to update dyndns ipv4 and ipv6 at the same time?
I use freedns.afraid.org service. My provider gives real dynamic IPv4 and real dynamic IPv6 (not broker).
I would like to use inadin only.

**Comment by lly-dev** [comment] 2016-02-15 10:45
duplicate of #473

**Closed by lly-dev** 2016-02-15 10:45 UTC
Labels: duplicate
